version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - webnet
    environment:
      - MONGODB_URI=mongodb://localhost:27017/PDFStore
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - webnet
  mongo:
    image: mongo:latest
    container_name: simplefrontendbackend-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
networks:
  webnet:
